### PR TITLE
fix: `zksyncSwap` component bug on 3.5-rollup-implementation

### LINKED ISSUE #157: [bug] couldn't display the arbitrum demo
截屏2023-11-22 22 30 25

### PR DESCRIPTION
**Pull request by TwilightLogic**
## Overview

This PR is to fix #157.

### Update the src link
截屏2023-11-22 23 25 35

### CODE REVIEW

File: components/ZksyncSwap.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ export default function ZksyncSwap() {
 					width: '330px',
```
Comment (WGB5445) [inline components/ZksyncSwap.js:16]: maybe we can set width big ?

**Review by WGB5445 — APPROVED** [review]
